// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, GPUParticleRender, GPUParticleRenderGLSL, Material, ObjectUtils, Program, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  GPUParticleRenderGLSL = require('lib/text!./GPUParticleRender.glsl');
  return GPUParticleRender = (function(_super) {
    __extends(GPUParticleRender, _super);

    function GPUParticleRender(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(GPUParticleRenderGLSL);
      defaults = {
        pointSize: 1,
        lightPos: Vec3.create(0, 0, 0),
        lightRadius: 1,
        particleColor: new Color(0.0, 0.4, 0.8, 1.0),
        lightColor: new Color(0.6, 0.8, 0.99, 1.0),
        particlePositions: null
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      GPUParticleRender.__super__.constructor.call(this, program, uniforms);
    }

    return GPUParticleRender;

  })(Material);
});
