// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, PolygonsMaterial, PolygonsMaterialGLSL, Program, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  PolygonsMaterialGLSL = require('lib/text!effects/PolygonsMaterial.glsl');
  return PolygonsMaterial = (function(_super) {
    __extends(PolygonsMaterial, _super);

    function PolygonsMaterial(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(PolygonsMaterialGLSL);
      defaults = {
        pointSize: 2,
        cutout: 1
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      PolygonsMaterial.__super__.constructor.call(this, program, uniforms);
    }

    return PolygonsMaterial;

  })(Material);
});
