// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Face3, Geometry, Mesh, PointRibbon, SolidColor, Vec3, _ref;
  _ref = require('pex/geom'), Vec3 = _ref.Vec3, Face3 = _ref.Face3, Geometry = _ref.Geometry;
  Mesh = require('pex/gl').Mesh;
  SolidColor = require('pex/materials').SolidColor;
  return PointRibbon = (function(_super) {
    __extends(PointRibbon, _super);

    function PointRibbon(_arg) {
      this.n = _arg.n, this.material = _arg.material, this.subdiv = _arg.subdiv, this.width = _arg.width, this.exp = _arg.exp;
      if (this.n == null) {
        this.n = 1;
      }
      if (this.subdiv == null) {
        this.subdiv = 1;
      }
      if (this.width == null) {
        this.width = 1;
      }
      this.points = [];
      if (this.material == null) {
        this.material = new SolidColor();
      }
      this.geom = new Geometry({
        vertices: true,
        normals: true,
        faces: true
      });
      PointRibbon.__super__.constructor.call(this, this.geom, this.material);
    }

    PointRibbon.prototype.draw = function(camera) {
      var faces, i, idx, j, needsFaces, normals, step, subStep, vertices, _i, _j, _k, _l, _m, _ref1, _ref2, _ref3, _ref4, _ref5;
      vertices = this.geom.vertices;
      vertices.dirty = true;
      normals = this.geom.normals;
      normals.dirty = true;
      faces = this.geom.faces;
      needsFaces = faces.length === 0;
      step = 1 / (this.n - 1);
      subStep = this.subdiv > 1 ? 1 / (this.subdiv - 1) : 0;
      idx = 0;
      for (i = _i = 0, _ref1 = this.n - 1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        j = 0;
        if (i < this.n - 1) {
          for (j = _j = 0, _ref2 = this.subdiv - 1; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; j = 0 <= _ref2 ? ++_j : --_j) {
            vertices[idx] = this.exp(i * this.subdiv + j, i * step + j * subStep * step, vertices[idx]);
            vertices[idx + 1] = this.exp(i * this.subdiv + j, i * step + j * subStep * step, vertices[idx + 1]);
            vertices[idx + 1].z -= this.width;
            idx += 2;
          }
        } else {
          vertices[idx] = this.exp(i * this.subdiv, i * step, vertices[idx]);
          vertices[idx + 1] = this.exp(i * this.subdiv, i * step, vertices[idx + 1]);
          vertices[idx + 1].z -= this.width;
          idx += 2;
        }
      }
      if (needsFaces) {
        for (i = _k = 0, _ref3 = vertices.length - 1; 0 <= _ref3 ? _k <= _ref3 : _k >= _ref3; i = 0 <= _ref3 ? ++_k : --_k) {
          normals[i] = new Vec3();
        }
      }
      if (this.ab == null) {
        this.ab = new Vec3();
      }
      if (this.ac == null) {
        this.ac = new Vec3();
      }
      for (i = _l = 0, _ref4 = vertices.length - 3; _l <= _ref4; i = _l += 2) {
        this.ab.asSub(vertices[i], vertices[i + 1]);
        this.ac.asSub(vertices[i], vertices[i + 2]);
        if ((this.ac.length() < 0.01) && vertices[i + 4]) {
          this.ac.asSub(vertices[i], vertices[i + 4]);
        }
        normals[i].asCross(this.ac, this.ab);
      }
      if (needsFaces) {
        for (i = _m = 0, _ref5 = vertices.length - 3; _m <= _ref5; i = _m += 2) {
          faces.push(new Face3(i, i + 3, i + 1));
          faces.push(new Face3(i, i + 2, i + 3));
        }
      }
      return PointRibbon.__super__.draw.call(this, camera);
    };

    return PointRibbon;

  })(Mesh);
});
