// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Edge, Geometry, LineBuilder, Mesh, PointCurve, SolidColor, Vec3, _ref;
  _ref = require('pex/geom'), Vec3 = _ref.Vec3, Edge = _ref.Edge, Geometry = _ref.Geometry;
  Mesh = require('pex/gl').Mesh;
  LineBuilder = require('pex/geom/gen').LineBuilder;
  SolidColor = require('pex/materials').SolidColor;
  return PointCurve = (function(_super) {
    __extends(PointCurve, _super);

    function PointCurve(_arg) {
      this.n = _arg.n, this.material = _arg.material, this.subdiv = _arg.subdiv, this.exp = _arg.exp;
      if (this.n == null) {
        this.n = 1;
      }
      if (this.subdiv == null) {
        this.subdiv = 1;
      }
      this.geom = new Geometry({
        vertices: true,
        edges: true,
        faces: false
      });
      if (this.material == null) {
        this.material = new SolidColor();
      }
      PointCurve.__super__.constructor.call(this, this.geom, this.material, {
        useEdges: true
      });
    }

    PointCurve.prototype.draw = function(camera) {
      var i, idx, j, needsEdges, step, subStep, vertices, _i, _j, _k, _ref1, _ref2, _ref3;
      vertices = this.geom.vertices;
      needsEdges = this.geom.edges.length === 0;
      step = 1 / (this.n - 1);
      subStep = this.subdiv > 1 ? 1 / (this.subdiv - 1) : 0;
      idx = 0;
      for (i = _i = 0, _ref1 = this.n - 1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        j = 0;
        if (i < this.n - 1) {
          for (j = _j = 0, _ref2 = this.subdiv - 1; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; j = 0 <= _ref2 ? ++_j : --_j) {
            vertices[idx] = this.exp(i * this.subdiv + j, i * step + j * subStep * step, vertices[idx]);
            idx++;
          }
        } else {
          vertices[idx] = this.exp(i * this.subdiv, i * step, vertices[idx]);
          idx++;
        }
      }
      if (needsEdges) {
        for (i = _k = 0, _ref3 = vertices.length - 2; 0 <= _ref3 ? _k <= _ref3 : _k >= _ref3; i = 0 <= _ref3 ? ++_k : --_k) {
          this.geom.edges.push(new Edge(i, i + 1));
        }
      }
      this.geom.vertices.dirty = true;
      return PointCurve.__super__.draw.call(this, camera);
    };

    return PointCurve;

  })(Mesh);
});
