// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, Program, RenderInScreenSpace, RenderInScreenSpaceGLSL, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  RenderInScreenSpaceGLSL = require('lib/text!materials/RenderInScreenSpace.glsl');
  return RenderInScreenSpace = (function(_super) {
    __extends(RenderInScreenSpace, _super);

    function RenderInScreenSpace(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(RenderInScreenSpaceGLSL);
      defaults = {
        ambientColor: Color.create(0, 0, 0, 1),
        diffuseColor: Color.create(1, 1, 1, 1),
        specularColor: Color.create(1, 1, 1, 1),
        lightPos: new Vec3(15, 5, 5),
        wrap: 1
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      RenderInScreenSpace.__super__.constructor.call(this, program, uniforms);
    }

    return RenderInScreenSpace;

  })(Material);
});

/*
//@ sourceMappingURL=RenderInScreenSpace.map
*/
