// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, Program, RGBDTExtured, RGBDTExturedGLSL, RGBDUtilsGLSL, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  RGBDTExturedGLSL = require('lib/text!materials/RGBDTextured.glsl');
  RGBDUtilsGLSL = require('lib/text!materials/RGBDUtils.inc.glsl');
  return RGBDTExtured = (function(_super) {
    __extends(RGBDTExtured, _super);

    function RGBDTExtured(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(RGBDUtilsGLSL + '\n' + RGBDTExturedGLSL);
      defaults = {
        maxDepth: 5999,
        opacity: 1,
        pointSize: 2,
        highlight: 0
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      RGBDTExtured.__super__.constructor.call(this, program, uniforms);
    }

    return RGBDTExtured;

  })(Material);
});
