// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, Program, ShowIsoLines, ShowIsoLinesGLSL, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  ShowIsoLinesGLSL = require('lib/text!materials/ShowIsoLines.glsl');
  return ShowIsoLines = (function(_super) {
    __extends(ShowIsoLines, _super);

    function ShowIsoLines(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(ShowIsoLinesGLSL);
      defaults = {
        distance: 0.05
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      ShowIsoLines.__super__.constructor.call(this, program, uniforms);
    }

    return ShowIsoLines;

  })(Material);
});

/*
//@ sourceMappingURL=ShowIsoLines.map
*/
