// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, Program, ShowDepthInScreenSpace, ShowDepthInScreenSpaceGLSL, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  ShowDepthInScreenSpaceGLSL = require('lib/text!materials/ShowDepthInScreenSpace.glsl');
  return ShowDepthInScreenSpace = (function(_super) {
    __extends(ShowDepthInScreenSpace, _super);

    function ShowDepthInScreenSpace(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(ShowDepthInScreenSpaceGLSL);
      defaults = {
        near: 0,
        far: 10,
        nearColor: Color.create(0, 0, 0, 1),
        farColor: Color.create(1, 1, 1, 1)
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      ShowDepthInScreenSpace.__super__.constructor.call(this, program, uniforms);
    }

    return ShowDepthInScreenSpace;

  })(Material);
});

/*
//@ sourceMappingURL=ShowDepthInScreenSpace.map
*/
