// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Material, ObjectUtils, Program, TexturedWithSeams, TexturedWithSeamsGLSL, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Color = require('pex/color/Color');
  TexturedWithSeamsGLSL = require('lib/text!materials/TexturedWithSeams.glsl');
  return TexturedWithSeams = (function(_super) {
    __extends(TexturedWithSeams, _super);

    function TexturedWithSeams(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(TexturedWithSeamsGLSL);
      defaults = uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      TexturedWithSeams.__super__.constructor.call(this, program, uniforms);
    }

    return TexturedWithSeams;

  })(Material);
});

/*
//@ sourceMappingURL=TexturedWithSeams.map
*/
