// Generated by CoffeeScript 1.6.2
define(function(require) {
  var BellCurve, pow, sin;

  pow = Math.pow, sin = Math.sin;
  return BellCurve = (function() {
    function BellCurve(scale, height) {
      this.scale = scale != null ? scale : 6;
      this.height = height != null ? height : 0.25;
    }

    BellCurve.prototype["eval"] = function(u, v, t) {
      var a, b, c, d, e, fx, fz, x, z;

      if (t == null) {
        t = 0;
      }
      a = this.height + 0.25 * sin(t);
      e = 2.71828;
      b = 0;
      c = 1;
      d = 0;
      x = u * this.scale;
      z = v * this.scale;
      fx = a * pow(e, -(x - b) * (x - b) / (2 * c * c)) + d;
      fz = a * pow(e, -(z - b) * (z - b) / (2 * c * c)) + d;
      return fx * fz;
    };

    return BellCurve;

  })();
});

/*
//@ sourceMappingURL=BellCurve.map
*/
