// Generated by CoffeeScript 1.6.2
define(function(require) {
  var BellCurve, Cosine, PI, cos, pow, sin;

  pow = Math.pow, sin = Math.sin, cos = Math.cos, PI = Math.PI;
  BellCurve = require('flora/land/surface/BellCurve');
  return Cosine = (function() {
    function Cosine(scale, height) {
      this.scale = scale != null ? scale : 2;
      this.height = height != null ? height : 0.25;
      this.bellCurve = new BellCurve(4, 1);
    }

    Cosine.prototype["eval"] = function(u, v, t) {
      var f, period;

      if (t == null) {
        t = 0;
      }
      period = 2;
      f = this.height * cos(this.scale * u * 2 * PI + t);
      f *= this.bellCurve["eval"](u, v);
      return f;
    };

    return Cosine;

  })();
});

/*
//@ sourceMappingURL=Cosine.map
*/
