// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Noise, PI, PerlinNoise, cos, pow, sin;

  pow = Math.pow, sin = Math.sin, cos = Math.cos, PI = Math.PI;
  PerlinNoise = require('lib/PerlinNoise');
  return Noise = (function() {
    function Noise(scale, height) {
      this.scale = scale != null ? scale : 5;
      this.height = height != null ? height : 0.25;
    }

    Noise.prototype["eval"] = function(u, v, t) {
      if (t == null) {
        t = 0;
      }
      return this.height * PerlinNoise.noise((u + 0.5) * this.scale, (v + 0.5 + t / 10) * this.scale, 0);
    };

    return Noise;

  })();
});

/*
//@ sourceMappingURL=Noise.map
*/
