// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Rule;

  return Rule = (function() {
    function Rule(input, output, probabilty) {
      this.input = input;
      this.output = output;
      this.probabilty = probabilty != null ? probabilty : 1;
    }

    return Rule;

  })();
});

/*
//@ sourceMappingURL=Rule.map
*/
