// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Algae, Cactus, Config, Flower, Fruit, GUI, GenesPanel, Grass, GrassInstanced, Herb, KnobsPanel, PlantType, Platform, Rect, Window, pex, _ref, _ref1, _ref2, _ref3;

  pex = require('pex');
  _ref = pex.sys, Window = _ref.Window, Platform = _ref.Platform;
  Rect = pex.geom.Rect;
  _ref1 = require('flora/game'), PlantType = _ref1.PlantType, Config = _ref1.Config;
  _ref2 = require('flora/game/ui'), GenesPanel = _ref2.GenesPanel, KnobsPanel = _ref2.KnobsPanel;
  _ref3 = require('flora/plants'), Fruit = _ref3.Fruit, Cactus = _ref3.Cactus, Herb = _ref3.Herb, Algae = _ref3.Algae, Grass = _ref3.Grass, Flower = _ref3.Flower;
  GrassInstanced = require('flora/plants/GrassInstanced');
  GUI = require('pex/gui/GUI');
  return Window.create({
    settings: {
      fullscreen: Platform.isEjecta,
      width: 1536 / 2.5,
      height: 2048 / 2.5
    },
    init: function() {
      return this.initUI();
    },
    initUI: function() {
      var plantIndex;

      plantIndex = 0;
      this.gui = new GUI(this, 5, 5, Platform.isEjecta ? 2 : 1);
      return this.cactus = new Cactus(this);
    },
    draw: function() {
      this.gl.clearColor(0, 0, 0, 1);
      this.gl.clear(this.gl.COLOR_BUFFER_BIT | this.gl.DEPTH_BUFFER_BIT);
      this.gl.disable(this.gl.DEPTH_TEST);
      this.cactus.draw();
      return this.gui.draw();
    }
  });
});

/*
//@ sourceMappingURL=FloraPlantTest.map
*/
