// Generated by CoffeeScript 1.6.2
define(function(require) {
  var game;

  return game = {
    PlantType: require('flora/game/PlantType'),
    Config: require('flora/game/Config')
  };
});

/*
//@ sourceMappingURL=game.map
*/
