// Generated by CoffeeScript 1.6.2
define(function(require) {
  var HEEdge, HEFace, HEMesh, HEVertex;

  HEMesh = require('pex/geom/hem/HEMesh');
  HEVertex = require('pex/geom/hem/HEVertex');
  HEFace = require('pex/geom/hem/HEFace');
  HEEdge = require('pex/geom/hem/HEEdge');
  HEMesh.prototype.dup = function() {
    var copy,
      _this = this;

    copy = new HEMesh();
    copy.vertices = this.vertices.map(function(v) {
      return new HEVertex(v.position.x, v.position.y, v.position.z);
    });
    copy.faces = this.faces.map(function() {
      return new HEFace();
    });
    copy.edges = this.edges.map(function() {
      return new HEEdge();
    });
    this.vertices.forEach(function(v, i) {
      return copy.vertices[i].edge = copy.edges[_this.edges.indexOf(v.edge)];
    });
    this.edges.forEach(function(e, i) {
      copy.edges[i].vert = copy.vertices[_this.vertices.indexOf(e.vert)];
      copy.edges[i].pair = copy.edges[_this.edges.indexOf(e.pair)];
      copy.edges[i].next = copy.edges[_this.edges.indexOf(e.next)];
      copy.edges[i].face = copy.faces[_this.faces.indexOf(e.face)];
      return copy.edges[i].face.edge = copy.edges[i];
    });
    return copy;
  };
  return HEMesh;
});

/*
//@ sourceMappingURL=HEDuplicate.map
*/
