// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Config, VideosPanel;

  Config = require('flora/game/Config');
  return VideosPanel = (function() {
    function VideosPanel() {
      var i, videoElements, _i;

      if (typeof document === 'undefined') {
        return;
      }
      videoElements = document.querySelectorAll("#videos video");
      this.professorVideo = document.querySelector("#professorVideo video");
      this.professorImage = document.querySelector("#professorVideo img");
      for (i = _i = 0; _i < 3; i = ++_i) {
        videoElements[i].setAttribute('src', Config.projection.videos[i].path);
        videoElements[i].parentNode.style.left = (40 + i * 297 + i * (1050 - 80 - 3 * 297) / 2) + 'px';
      }
      this.professorVideo.setAttribute('src', Config.projection.professorVideo.path);
      this.professorVideoOpacity = 0;
    }

    VideosPanel.prototype.showFeedback = function(state) {
      if (typeof document === 'undefined') {
        return;
      }
      this.professorVideoOpacity = state ? 1 : 0;
      this.professorVideo.style.opacity = this.professorVideoOpacity;
      return this.professorImage.style.opacity = this.professorVideoOpacity;
    };

    return VideosPanel;

  })();
});

/*
//@ sourceMappingURL=VideosPanel.map
*/
