// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Context, Geometry, MathUtils, Mesh, NormalsDistort, NormalsDistortMaterial, TextureCube, Vec2, _ref, _ref1;

  Context = require('pex/gl').Context;
  _ref = require('pex/geom'), Geometry = _ref.Geometry, Vec2 = _ref.Vec2;
  _ref1 = require('pex/gl'), Mesh = _ref1.Mesh, TextureCube = _ref1.TextureCube;
  MathUtils = require('pex/utils').MathUtils;
  NormalsDistortMaterial = require('effects/NormalsDistortMaterial');
  return NormalsDistort = (function() {
    NormalsDistort.prototype.amount = 1;

    NormalsDistort.prototype.amountMouse = 0;

    function NormalsDistort(app, source, boundingBox, rgbdTexture) {
      var geom, gl, h, i, material, s, t, w, _i, _ref2;

      this.app = app;
      this.source = source;
      this.boundingBox = boundingBox;
      this.rgbdTexture = rgbdTexture;
      gl = this.gl = Context.currentContext.gl;
      geom = new Geometry({
        vertices: true,
        texCoords: true,
        faces: false
      });
      w = this.source.textureSize.x;
      h = this.source.textureSize.y;
      for (i = _i = 0, _ref2 = w * h / 2 - 1; _i <= _ref2; i = _i += 1) {
        s = (i % w) / w + Math.random() * 0.1;
        t = Math.floor(i / w) / (h / 2) + Math.random() * 0.1;
        geom.vertices.push(MathUtils.randomVec3().scale(3000));
        geom.texCoords.push(new Vec2(s, t));
      }
      material = new NormalsDistortMaterial({
        pointSize: 2,
        rgbd: this.rgbdTexture,
        bboxMin: this.source.boundingBox.min,
        bboxMax: this.source.boundingBox.max,
        bboxCenter: this.source.boundingBox.getCenter(),
        amount: this.amount,
        amountMouse: this.amountMouse
      });
      this.mesh = new Mesh(geom, material, {
        primitiveType: gl.POINTS
      });
    }

    NormalsDistort.prototype.draw = function(camera) {
      this.gl.enable(this.gl.DEPTH_TEST);
      this.gl.enable(this.gl.BLEND);
      this.gl.blendFunc(this.gl.SRC_ALPHA, this.gl.ONE);
      this.mesh.material.uniforms.amount = this.amount;
      this.mesh.material.uniforms.amountMouse = this.amountMouse;
      return this.mesh.draw(camera);
    };

    return NormalsDistort;

  })();
});
