// Generated by CoffeeScript 1.6.2
define(function(require) {
  var IO, RGBDConfig;

  IO = require('pex/sys').IO;
  return RGBDConfig = (function() {
    function RGBDConfig() {}

    RGBDConfig.load = function(path, callback) {
      return IO.loadTextFile(path, function(xml) {
        var config;

        config = this.parse(xml);
        if (callback) {
          return callback(config);
        }
      });
    };

    RGBDConfig.parse = function(xml) {
      var config, lines;

      config = {};
      lines = xml.split('\n');
      lines.forEach(function(line) {
        var match, tagName, tagValue;

        match = line.match(/<([^>]+)>([^<]+)<\/([^>]+)>/);
        if (match) {
          tagName = match[1];
          tagValue = match[2];
          return config[tagName] = Number(tagValue);
        }
      });
      return config;
    };

    return RGBDConfig;

  })();
});
