var FXStage = require('pex-fx').FXStage;
var fs = require('fs');

var PBRGLSL = fs.readFileSync(__dirname + '/PBR2.glsl', 'utf8');

FXStage.prototype.pbr = function (options) {
  options = options || {};
  var outputSize = this.getOutputSize(options.width, options.height);
  var rt = this.getRenderTarget(outputSize.width, outputSize.height, options.depth, options.bpp);
  rt.bind();
  this.getSourceTexture(options.normalMap).bind(0);
  this.getSourceTexture(options.depthMap).bind(1);
  this.getSourceTexture(options.albedoMap).bind(2);
  this.getSourceTexture(options.occlusionMap).bind(3);
  this.getSourceTexture(options.reflectionMap).bind(4);
  this.getSourceTexture(options.specularMap).bind(5);
  var program = this.getShader(PBRGLSL);
  program.use();
  program.uniforms.normalMap(0);
  program.uniforms.depthMap(1);
  program.uniforms.albedoMap(2);
  program.uniforms.occlusionMap(3);
  if (program.uniforms.reflectionMap) program.uniforms.reflectionMap(4);
  if (program.uniforms.specularMap) program.uniforms.specularMap(5);
  if (program.uniforms.near) program.uniforms.near(options.camera.getNear());
  if (program.uniforms.far) program.uniforms.far(options.camera.getFar());
  if (program.uniforms.fov) program.uniforms.fov(options.camera.getFov());
  if (program.uniforms.aspectRatio) program.uniforms.aspectRatio(options.camera.getAspectRatio());
  program.uniforms.viewMatrix(options.camera.getViewMatrix());
  if (program.uniforms.invViewMatrix) program.uniforms.invViewMatrix(options.camera.getViewMatrix().dup().invert());
  if (program.uniforms.invProjectionMatrix) program.uniforms.invProjectionMatrix(options.camera.getProjectionMatrix().dup().invert());
  program.uniforms.lightPos(options.lightPos);
  program.uniforms.fogColor(options.fogColor);
  program.uniforms.fogDensity(options.fogDensity);
  program.uniforms.fogStart(options.fogStart);
  program.uniforms.fogOffset(options.fogOffset);
  program.uniforms.fogForegroundDensity(options.fogForegroundDensity);
  program.uniforms.lightBrightness(options.lightBrightness);
  program.uniforms.ssaoEnabled(options.ssaoEnabled ? 1 : 0);
  program.uniforms.indirectDiffuseEnabled(options.indirectDiffuseEnabled ? 1 : 0);
  program.uniforms.indirectSpecularEnabled(options.indirectSpecularEnabled ? 1 : 0);
  program.uniforms.directDiffuseEnabled(options.directDiffuseEnabled ? 1 : 0);
  program.uniforms.directSpecularEnabled(options.directSpecularEnabled ? 1 : 0);
  program.uniforms.ssaoEnabled(options.ssaoEnabled ? 1 : 0);
  program.uniforms.fogEnabled(options.fogEnabled ? 1 : 0);
  this.drawFullScreenQuad(outputSize.width, outputSize.height, null, program);
  rt.unbind();
  return this.asFXStage(rt, 'pbr');
};

module.exports = FXStage;