// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var AllFacesSelector, FaceSelector;

  FaceSelector = require('flora/plants/modular/FaceSelector');
  return AllFacesSelector = (function(_super) {
    __extends(AllFacesSelector, _super);

    function AllFacesSelector() {
      this.faces = [];
    }

    AllFacesSelector.prototype.apply = function(hem, face) {
      var _i, _len, _ref;

      _ref = hem.faces;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        face = _ref[_i];
        this.faces.push(face);
      }
      return this.done = true;
    };

    return AllFacesSelector;

  })(FaceSelector);
});

/*
//@ sourceMappingURL=AllFacesSelector.map
*/
