// Generated by CoffeeScript 1.6.2
define(function(require) {
  var FaceSelector;

  return FaceSelector = (function() {
    function FaceSelector() {}

    return FaceSelector;

  })();
});

/*
//@ sourceMappingURL=FaceSelector.map
*/
