// Generated by CoffeeScript 1.6.2
define(function(require) {
  var NeighbourFaces;

  return NeighbourFaces = (function() {
    function NeighbourFaces() {
      this.faces = [];
    }

    NeighbourFaces.prototype.apply = function(hem, face) {
      var _this = this;

      return face.edgePairLoop(function(edge) {
        return _this.faces.push(edge.pair.face);
      });
    };

    return NeighbourFaces;

  })();
});

/*
//@ sourceMappingURL=NeighbourFaces.map
*/
