// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var FaceSelector, RandomFaceSelector;

  FaceSelector = require('flora/plants/modular/FaceSelector');
  return RandomFaceSelector = (function(_super) {
    __extends(RandomFaceSelector, _super);

    function RandomFaceSelector() {
      this.faces = [];
    }

    RandomFaceSelector.prototype.apply = function(hem, face) {
      this.faces.push(randomElement(hem.faces));
      return this.done = true;
    };

    return RandomFaceSelector;

  })(FaceSelector);
});

/*
//@ sourceMappingURL=RandomFaceSelector.map
*/
