// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Split2, Time, floor;

  Time = require('pex/utils/Time');
  floor = Math.floor;
  return Split2 = (function() {
    function Split2(distance, duration) {
      this.distance = distance != null ? distance : 0.1;
      this.duration = duration != null ? duration : 0.24;
      this.faces = [];
      this.progress = 0;
    }

    Split2.prototype.apply = function(hem, face) {
      var edges;

      edges = [];
      face.edgePairLoop(function(edge) {
        return edges.push(edge);
      });
      this.edge1 = edges[0];
      this.edge2 = edges[floor(edges.length / 2)];
      hem.splitEdge(this.edge1, 0.5);
      hem.splitEdge(this.edge2, 0.5);
      hem.splitFace(this.edge1.next, this.edge2.next);
      this.normal = this.edge1.face.getNormal();
      this.faces.push(this.edge1.face);
      return this.faces.push(this.edge2.face);
    };

    Split2.prototype.update = function() {
      var d;

      d = Time.delta * this.distance / this.duration;
      this.normal.normalize().scale(d);
      this.progress += Time.delta / this.duration;
      if (this.progress > 1) {
        this.done = true;
      }
      this.edge1.next.vert.position.add(this.normal);
      return this.edge2.next.vert.position.add(this.normal);
    };

    return Split2;

  })();
});

/*
//@ sourceMappingURL=Split2.map
*/
