// Generated by CoffeeScript 1.6.2
var PI, abs, cos, exp, log, max, min, plask, pow, sin;

plask = require('plask');

sin = Math.sin, cos = Math.cos, abs = Math.abs, PI = Math.PI, max = Math.max, log = Math.log, pow = Math.pow, exp = Math.exp, min = Math.min;

plask.simpleWindow({
  settings: {
    width: 800,
    height: 600
  },
  init: function() {},
  draw: function() {
    var a, clamp, cx, cy, maxR, mix, r, smin, smin2, smin3, x, y, _i, _j, _ref, _ref1, _results;

    this.canvas.drawColor(50, 50, 50, 255);
    this.paint.setFill();
    this.paint.setColor(255, 255, 255, 255);
    cx = this.width / 2;
    cy = this.height / 2;
    maxR = 150;
    r = maxR;
    for (a = _i = 0, _ref = PI / 36; _ref > 0 ? _i <= PI : _i >= PI; a = _i += _ref) {
      r = maxR * (1 - cos(a));
      x = cx + r * cos(a);
      y = cy + r * sin(a);
      this.canvas.drawRect(this.paint, x - 1, y - 1, x + 2, y + 2);
    }
    this.paint.setColor(0, 255, 255, 255);
    clamp = function(a, lo, hi) {
      if (a < lo) {
        lo;
      }
      if (a > hi) {
        hi;
      }
      return a;
    };
    mix = function(a, b, t) {
      return a + (b - a) * t;
    };
    smin = function(a, b, k) {
      var res;

      a = -a;
      b = -b;
      res = exp(-k * a) + exp(-k * b);
      return log(res) / k;
    };
    smin2 = function(a, b, k) {
      var h;

      a = -a;
      b = -b;
      h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
      return -mix(b, a, h) - k * h * (1.0 - h);
    };
    smin3 = function(a, b, k) {
      a = 1 - a;
      b = 1 - b;
      a = pow(a, k);
      b = pow(b, k);
      return 1.0 - pow((a * b) / (a + b), 1.0 / k);
    };
    _results = [];
    for (a = _j = -0, _ref1 = PI / 100; _j <= 3; a = _j += _ref1) {
      x = cx + this.width / 2 * a / 3 - 200;
      y = cy - 100 * smin3(0.5 * max(0, sin(a * 2)), 0.95 * max(0, sin(a * 2 - 2.3)), 2);
      _results.push(this.canvas.drawRect(this.paint, x - 1, y - 1, x + 2, y + 2));
    }
    return _results;
  }
});

/*
//@ sourceMappingURL=FruitTest.map
*/
