// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Instance, Quat, UP, Vec3, randomVec3, _ref;

  _ref = require('pex/geom'), Vec3 = _ref.Vec3, Quat = _ref.Quat;
  randomVec3 = require('pex/utils/MathUtils').randomVec3;
  UP = new Vec3(0, 1, 0);
  return Instance = (function() {
    function Instance(spread, scale) {
      if (spread == null) {
        spread = 0.00001;
      }
      if (scale == null) {
        scale = 0.0;
      }
      this.targetPosition = randomVec3(spread);
      this.targetRotation = new Quat().setAxisAngle(UP, 0);
      this.targetScale = new Vec3(scale, scale, scale);
      this.position = new Vec3(0, 0, 0);
      this.rotation = new Quat().setAxisAngle(UP, 0);
      this.scale = new Vec3(0, 0, 0);
    }

    Instance.prototype.update = function() {
      this.position.x += (this.targetPosition.x - this.position.x) * 0.1;
      this.position.y += (this.targetPosition.y - this.position.y) * 0.1;
      this.position.z += (this.targetPosition.z - this.position.z) * 0.1;
      this.scale.x += (this.targetScale.x - this.scale.x) * 0.1;
      this.scale.y += (this.targetScale.y - this.scale.y) * 0.1;
      this.scale.z += (this.targetScale.z - this.scale.z) * 0.1;
      return this.rotation.slerp(this.targetRotation, 0.1, false);
    };

    return Instance;

  })();
});

/*
//@ sourceMappingURL=Instance.map
*/
