// Generated by CoffeeScript 1.6.2
define(function(require) {
  var exports;

  return exports = {
    LSystem: require('flora/plants/lsys/LSystem'),
    LSystemRenderer: require('flora/plants/lsys/LSystemRenderer'),
    Rule: require('flora/plants/lsys/Rule')
  };
});

/*
//@ sourceMappingURL=lsys.map
*/
