// Generated by CoffeeScript 1.6.2
define(function(require) {
  var plants;

  return plants = {
    Fruit: require('flora/plants/Fruit'),
    Herb: require('flora/plants/Herb'),
    Cactus: require('flora/plants/Cactus')
  };
});

/*
//@ sourceMappingURL=plants.map
*/
