// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Agent, Vec3;

  Vec3 = require('pex/geom').Vec3;
  return Agent = (function() {
    function Agent(position) {
      this.position = position != null ? position : new Vec3(0, 0, 0);
      this.velocity = new Vec3(0, 0, 0);
      this.forces = [];
      this.points = [];
      this.points.push(this.position.dup());
    }

    Agent.prototype.updateSteps = function(n, speed) {
      var force, i, _i, _j, _len, _ref, _results;

      _results = [];
      for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
        _ref = this.forces;
        for (_j = 0, _len = _ref.length; _j < _len; _j++) {
          force = _ref[_j];
          this.velocity.add(force.dup().scale(speed));
        }
        this.position.add(this.velocity.dup().scale(speed));
        _results.push(this.points.push(this.position.dup()));
      }
      return _results;
    };

    return Agent;

  })();
});

/*
//@ sourceMappingURL=Agent.map
*/
