// Generated by CoffeeScript 1.6.2
define(function(require) {
  var AnimatedVec3, Vec3;

  Vec3 = require('pex/geom/Vec3');
  return AnimatedVec3 = (function() {
    function AnimatedVec3(v) {
      this.initialValue = v.dup();
      this.value = v.dup();
      this.target = v.dup();
    }

    AnimatedVec3.prototype.update = function() {
      this.value.x += (this.target.x - this.value.x) * 0.1;
      this.value.y += (this.target.y - this.value.y) * 0.1;
      return this.value.z += (this.target.z - this.value.z) * 0.1;
    };

    return AnimatedVec3;

  })();
});

/*
//@ sourceMappingURL=AnimatedVec3.map
*/
