// Generated by CoffeeScript 1.6.2
define(function(require) {
  var BFSOCtreeIterator;

  return BFSOCtreeIterator = (function() {
    function BFSOCtreeIterator(octree) {
      this.octree = octree;
      this.stack = [this.octree.root];
    }

    BFSOCtreeIterator.prototype.next = function() {
      var cell, childCell, _i, _len, _ref;

      cell = this.stack.shift();
      if (cell) {
        _ref = cell.children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          childCell = _ref[_i];
          this.stack.push(childCell);
        }
      }
      return cell;
    };

    BFSOCtreeIterator.prototype.reset = function() {
      this.stack.length = 0;
      return this.stack.push(this.octree.root);
    };

    return BFSOCtreeIterator;

  })();
});
