// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Color, Context, Mat4, Material, ObjectUtils, OctreeTracerMaterial, OctreeTracerMaterialGLSL, Program, Vec3;

  Material = require('pex/materials/Material');
  Context = require('pex/gl/Context');
  Program = require('pex/gl/Program');
  ObjectUtils = require('pex/utils/ObjectUtils');
  Vec3 = require('pex/geom/Vec3');
  Mat4 = require('pex/geom/Mat4');
  Color = require('pex/color/Color');
  OctreeTracerMaterialGLSL = require('lib/text!./OctreeTracerMaterial.glsl');
  return OctreeTracerMaterial = (function(_super) {
    __extends(OctreeTracerMaterial, _super);

    function OctreeTracerMaterial(uniforms) {
      var defaults, program;

      this.gl = Context.currentContext.gl;
      program = new Program(OctreeTracerMaterialGLSL);
      defaults = {
        invViewMatrix: new Mat4()
      };
      uniforms = ObjectUtils.mergeObjects(defaults, uniforms);
      OctreeTracerMaterial.__super__.constructor.call(this, program, uniforms);
    }

    return OctreeTracerMaterial;

  })(Material);
});
